name: samples-yaml-to-arm
on:
  push:
    branches: [working]
    paths:
      - Samples/**
  workflow_dispatch:
permissions:
  contents: write
jobs:
  template:
    name: YamlTo-ARM
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: SecureHats template
        uses: SecureHats/YamlTo-Arm@v0.1.7
        with:
          filesPath: ./Samples
          outputPath: ./Analytics
      - name: Commit and push changes
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add Analytics

          # Don't fail if nothing changed
          git diff --cached --quiet && echo "No changes to commit" && exit 0

          git commit -m "Automated: Convert YAML -> ARM"
          git push
