name: Deploy Content to sentinel-logs [ed73377a-0fb3-4e3c-bece-3b93390ed59f]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-ed73377a-0fb3-4e3c-bece-3b93390ed59f.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-ed73377a-0fb3-4e3c-bece-3b93390ed59f.yml'


jobs:
  convert-yaml-to-arm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Convert rules to ARM
        shell: pwsh
        run: |
          Install-Module SentinelARConverter -AcceptLicense -Force
          Get-ChildItem -Path 'Analytics' -Filter '*.yaml' | ForEach-Object {
            Convert-SentinelARYamlToArm -Filename $_.FullName -UseOriginalFilename
          }

      - name: Upload generated ARM
        uses: actions/upload-artifact@v4
        with:
          name: sentinel-arm
          path: Analytics/**/*.json

  deploy-content:
    runs-on: windows-latest
    needs: convert-yaml-to-arm
    env:
      resourceGroupName: 'rg-sentinel'
      workspaceName: 'sentinel-logs'
      workspaceId: '3a321edd-c618-4ac7-affc-a5ffe70f7b20'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'AnalyticsRule,AutomationRule,HuntingQuery,Parser,Playbook,Workbook'
      branch: 'main'
      sourceControlId: 'ed73377a-0fb3-4e3c-bece-3b93390ed59f'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - uses: actions/checkout@v4
    
    - name: Download generated ARM
      uses: actions/download-artifact@v4
      with:
        name: sentinel-arm
        path: Analytics

    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_ed73377a0fb34e3cbece3b93390ed59f }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_ed73377a0fb34e3cbece3b93390ed59f }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_ed73377a0fb34e3cbece3b93390ed59f }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_ed73377a0fb34e3cbece3b93390ed59f }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_ed73377a0fb34e3cbece3b93390ed59f }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_ed73377a0fb34e3cbece3b93390ed59f }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_ed73377a0fb34e3cbece3b93390ed59f }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_ed73377a0fb34e3cbece3b93390ed59f }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_ed73377a0fb34e3cbece3b93390ed59f }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-ed73377a-0fb3-4e3c-bece-3b93390ed59f.ps1